

-- 1. Routes Table      y
CREATE TABLE Routes (
    RouteID               INTEGER        PRIMARY KEY,
    RouteDescription      VARCHAR2(255)
);





SELECT * FROM  ROUTES;

-- 2. Stations Table   y
CREATE TABLE Stations (
    StationID             VARCHAR2(5)    PRIMARY KEY,
    StationCity           VARCHAR2(50)   NOT NULL
);



DROP TABLE CUSTOMERS

-- 3. Customers Table     y
CREATE TABLE Customers (
    CustomerID            VARCHAR2(20)        PRIMARY KEY,
    Email                 VARCHAR2(50)   UNIQUE,
    PassKey               VARCHAR2(20)   NOT NULL,
    FullName              VARCHAR2(100)  NOT NULL,
    Age                   INTEGER        NOT NULL,
    Phone                 CHAR(10)       UNIQUE NOT NULL,
    PaymentAccount        VARCHAR2(100)
);





-- 4. Trains Table    y
CREATE TABLE Trains (
    TrainID               INTEGER        PRIMARY KEY,
    TrainName             VARCHAR2(60)   NOT NULL,
    AvailableSeats        INTEGER,
    RouteID               INTEGER,

    CONSTRAINT fk_routeid FOREIGN KEY (RouteID) REFERENCES Routes(RouteID)
);



SELECT * FROM Trains WHERE TrainID = 13452;



-- 5. RouteStations Table    y
CREATE TABLE RouteStations (
    RouteStationID        INTEGER        PRIMARY KEY,
    RouteID               INTEGER,
    StartingStationID     VARCHAR2(5)    NOT NULL,
    IntermediateStationID VARCHAR2(5),
    EndingStationID       VARCHAR2(5)    NOT NULL,
    DistanceCovered       INTEGER        NOT NULL,

    CONSTRAINT fk_route_id FOREIGN KEY (RouteID) REFERENCES Routes(RouteID),
    CONSTRAINT fk_start_station FOREIGN KEY (StartingStationID) REFERENCES Stations(StationID),
    CONSTRAINT fk_intermediate_station FOREIGN KEY (IntermediateStationID) REFERENCES Stations(StationID),
    CONSTRAINT fk_end_station FOREIGN KEY (EndingStationID) REFERENCES Stations(StationID)
);


 DROP TABLE AvailabilitySchedule;






-- 6. Bookings Table    y

CREATE TABLE Bookings (
    BookingID             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PassengerFullName     VARCHAR2(100),
    CustomerID            VARCHAR2(20) ,
    BookingDate           DATE           NOT NULL,
    BoardingStationID     VARCHAR2(5)    NOT NULL,
    EndingStationID       VARCHAR2(5)    NOT NULL,
    Fare                  DECIMAL(10, 3),
    DateOfJourney         DATE           NOT NULL,
    Gender                CHAR(1)        NOT NULL,
    Age                   INTEGER        CHECK (Age >= 0) NOT NULL,
    PaymentStatus         CHAR(1)        CHECK (PaymentStatus IN ('1', '0')),
    TrainID               INTEGER,
    TrainName             VARCHAR2(50),
    TransactionID         VARCHAR2(70),
    SeatAlloted           CHAR(1),

    CONSTRAINT fk_b_stationid FOREIGN KEY (BoardingStationID) REFERENCES Stations(StationID),
    CONSTRAINT fk_e_stationid FOREIGN KEY (EndingStationID) REFERENCES Stations(StationID),
    CONSTRAINT fk_customerid FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID),
    CONSTRAINT fk_trainid FOREIGN KEY (TrainID) REFERENCES Trains(TrainID)
);


DROP TABLE Bookings
DROP TABLE Cancelation

-- 7. Cancellation Table  y

Create table Cancelation (

    CancellationID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BookingID             NUMBER ,
    CancellationDate      TIMESTAMP,
    CancellationAmt       DECIMAL,

    CONSTRAINT fk_bookingCanclation FOREIGN KEY (BookingID) REFERENCES Bookings(BookingID)


)







--8. AvailibilityTimingBridge 

CREATE TABLE AvailibilityTimingBridge (
                
        TimingID              CHAR(8) PRIMARY KEY
    
)






-- 9.. AvailabilitySchedule Table 

CREATE TABLE AvailabilitySchedule (
    AvailabilityKey       INTEGER PRIMARY KEY,
    TrainID               INTEGER,
    TimingID              CHAR(8),
    AvailableDays         CHAR(3),
    ScheduledDate         DATE,
    RunningStatus         CHAR(1),
    AvailableSeats        INT,
    CONSTRAINT fk_train_timing_av  FOREIGN KEY (TimingID) REFERENCES AvailibilityTimingBridge(TimingID),
    CONSTRAINT fk_train_id_fk      FOREIGN KEY (TrainID)  REFERENCES Trains(TrainID)
);








 DROP TABLE TrainTiming;

-- 10. TrainSchedule Table 

CREATE TABLE TrainTiming (
    
    TrainTimingID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TimingID              CHAR(8),
    RouteStationID        INTEGER,
    ArrivalTime           TIMESTAMP,
    DepartureTime         TIMESTAMP,

    CONSTRAINT fk_train_timing_2  FOREIGN KEY (TimingID) REFERENCES AvailibilityTimingBridge(TimingID),
    CONSTRAINT fk_route_station FOREIGN KEY (RouteStationID) REFERENCES RouteStations(RouteStationID)
);


















  

  DROP TABLE  TrainSchedule




COMMIT;



DROP TABLE TrainTiming;
DROP TABLE AvailabilitySchedule;
DROP TABLE RouteStations;
DROP TABLE Bookings;
DROP TABLE Trains;
DROP TABLE Stations;
DROP TABLE Customers;
DROP TABLE Routes;